<?php

namespace AppBundle\Repository;

/**
 * CarnetLiaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarnetLiaisonRepository extends \Doctrine\ORM\EntityRepository
{
}
